### PR TITLE
Provide option for additional language definition paths

### PR DESCRIPTION
**Pull request by em-eight**
The extra paths are specified from the command line. Maybe not the cleanest option since the main ghidra path setting in on the UI, but the extra paths are a list so it might require a lot of UI to implement

### CODE REVIEW

**Comment by LukeSerne** [comment]
Thanks for submitting a pull request! While the program currently has no command-line arguments, adding one is no problem. It'd indeed be better to eventually move this setting to something that can be configured though the UI, similarly to the ghidra path, but that can also be done after this PR has been merged.

The code looks good - just 3 minor nitpicks:
1. You consistently write `extrapaths` - I'd prefer splitting that into `extra-paths` (for the command line argument) and `extra_paths` (for the variable name).

2. In the edited `utils.get_decompile_data`, you construct the first argument to `subprocess.run` in a bit of a roundabout way (and in a way that'd break if there are spaces in any of the paths involved) because you first convert the list of path strings to a single string, only to split it into a list of strings before it is passed to `subprocess.run`. I think it'd be cleaner (and less buggy) to just construct the list directly. The below code, which is a bit cryptic without comment, accomplishes this.
```py
# Construct the full command, including extra paths for language
# definitions. The resulting command will be [decomp_path] if no extra_paths
# are given, and [decomp_path, '-s', path_1, '-s', path_2] if 2 extra_paths
# are given.
command_args = zip(['-s'] * len(extra_paths), extra_paths)
command = [decomp_path] + list(itertools.chain.from_iterable(command_args))
```

3. It'd be nice if you'd document the command line argument in the readme, and maybe also write something about what the `ldef`s are used for by the decompiler.

Thanks again for taking the time to contribute and submit a PR!

**Comment by em-eight** [comment]
Sure, addressed.
I was using the `extrapaths` name influenced from the name the decompiler uses internally for those paths.
For the path parsing, in which case is it buggy? It the paths contain spaces, argparse will consider them as separate paths anyway.

**Comment by LukeSerne** [comment]
Thanks for making the requested changes. Regarding the buggy behaviour: You can specify a path with spaces by wrapping the path in quotes. In the old version, running the program using the command `python main.py -s './test folder'`, the first argument to `subprocess.run` was `['/path/to/decomp_dbg', '-s', './test', 'folder']`. Here, the path is broken up, and the decompiler will not look for ldefs in the correct folder. In the new version, that argument is `['/path/to/decomp_dbg', '-s', './test folder']`.

**Comment by em-eight** [comment]
Ah tru

**Pull request merged**
